# Sample YAML configuration for a team table service

teams:
  - name: KKR
    matches:
      - wins:
        - RR
        - RCB
        - KKR
      - losses:
        - DC
        - GT
      - suspend:
        - MI
  - name: SRH
    matches:
      - wins:
        - GT
        - MI
      - losses:
        - DC
        - RCB
      - suspend:
        - PBKS
settings:
  max_teams: 10
  allow_duplicates: false