# Sample YAML configuration for a team table service

teams:
  - name: KKR
    matches:
      - opponent: RR
        score: 2
      - opponent: RCB
        score: 2
      - opponent: KKR
        score: 2
      - opponent: DC
        score: 0
      - opponent: GT
        score: 0
      - opponent: MI
        score: 1
  - name: SRH
    matches:
      - opponent: GT
        score: 2
      - opponent: MI
        score: 2
      - opponent: DC
        score: 0
      - opponent: RR
        score: 0
      - opponent: PBKS
        score: 1
  - name: RR
    matches:
      - opponent: KKR
        score: 0
      - opponent: SRH
        score: 2
      - opponent: DC
        score: 0
      - opponent: RCB
        score: 0
      - opponent: PBKS
        score: 1
settings:
  max_teams: 10
  allow_duplicates: false